### ISSUE TITLE
arguments 可以使用 for...of 遍历

### ISSUE THREAD

**Issue by Yawenina** [hawx1993/Front-end-Interview-Questions#25]
在 [ES6相关--Symbol, Map, Set](http://hawx1993.github.io/Front-end-Interview-Questions/#/?id=symbol%ef%bc%8cmap%e5%92%8cset) 这一板块中的最后提到：

> arguments本身不是可迭代对象，不能用for...of遍历

可是在[MDN 文档](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/for...of)中描述： `arguments` 是可迭代对象，可以使用 `for...of`进行遍历

测试：
![](http://obdn47xbq.bkt.clouddn.com/2017-09-14_11-51-26.png)

1. `arguments` 可以使用 `for...of`遍历；
2. `arguments`部署了`Symbol.iterator`接口，是可迭代对象。

很感谢你的文档！！

**Comment by hawx1993** [comment]
好的   是我记错了
