### ISSUE TITLE
您好，看见你有使用我这边收集的一些面试题片段，但有些没更新。

### ISSUE THREAD

**Issue by markyun** [hawx1993/Front-end-Interview-questions#5]
面试题原出处：https://github.com/markyun/My-blog/tree/master/Front-end-Developer-Questions

有些答案有错误的地方 ，希望作者及时更新。

**Comment by alex44jzy** [comment]
嗯 之前看过 感觉还可以的 给力

**Comment by SunShinewyf** [comment]
好的，谢谢你的分享，赞一个
  

 

 ------------------ 原始邮件 ------------------
  发件人: "马云云_理想青年";<notifications@github.com>;
 发送时间: 2015年10月21日(星期三) 下午2:41
 收件人: "hawx1993/Front-end-Interview-questions"<Front-end-Interview-questions@noreply.github.com>; 
 
 主题: Re: [Front-end-Interview-questions] 您好，看见你有使用我这边收集的一些面试题片段，但有些没更新。 (#5)

 

 
Closed #5.
